#!/usr/bin/env python3
"""Generate the library-counts block in README_TAPP_for_Schema_Generation.md.

  python3 build_schema_spec_counts.py            # --check: report drift, change nothing
  python3 build_schema_spec_counts.py --apply    # rewrite the block

WHY THIS EXISTS. The schema spec is the live document handed to the schema developer, and on
2026-09-08 every count in it had drifted -- the (none) share by 9 points, the Column G share by 32,
and one key (`acquisition pass`) was described as retired on the day it went into use, which would
have made a consumer drop an array of 92 rows. The file already told its reader "recount before you
rely on it". That advice is correct and insufficient: nobody recounts on advice. Counts an outside
consumer depends on are generated here instead, and `validate_tapp.py` fails on drift
(`schema-spec-stale-counts`, ERROR) so the block cannot go stale silently again.

WHAT BELONGS IN THE BLOCK. Anything that changes when a TAPP changes. Prose outside the markers must
stay true across drift -- say "a third of fields", not "33%", and let the block carry the figure.
"""
import csv, glob, os, re, sys
from collections import Counter, defaultdict

ROOT = "/Users/ruolin/Documents/Astromat/TAPPs"
SPEC = os.path.join(ROOT, "README_TAPP_for_Schema_Generation.md")
BEGIN = "<!-- BEGIN GENERATED library-counts -->"
END = "<!-- END GENERATED library-counts -->"
RETIRED = ["conversion", "background position", "model component"]


def collect(root=ROOT):
    keys = Counter(); rows = 0; stamped = 0
    per_field = defaultdict(set); definers = defaultdict(set); tapps = 0
    for p in sorted(glob.glob(os.path.join(root, "Current TAPPs", "*.csv"))):
        tapps += 1
        for r in list(csv.reader(open(p, newline="", encoding="utf-8-sig")))[1:]:
            # a group header carries a name but no key; only content rows count
            if not r or not r[0].strip() or len(r) < 9 or not r[8].strip():
                continue
            rows += 1
            k = r[8].strip(); keys[k] += 1
            per_field[r[0].strip()].add(k)
            if r[6].strip().startswith("Source:"):
                stamped += 1
            if k.startswith("defines:"):
                definers[r[0].strip()].add(k)
    return keys, rows, stamped, per_field, definers, tapps


def render(root=ROOT):
    keys, rows, stamped, per_field, definers, tapps = collect(root)
    scalar = keys.get("(none)", 0)
    # a key IN USE is one some field is keyed BY -- the bare domains, not the defines: forms
    in_use = set()
    for k in keys:
        if k.startswith("defines:"):
            continue
        for part in re.split(r"\s+[x>]\s+|^pair:\s*", k):
            part = part.strip()
            if part and part != "(none)":
                in_use.add(part)
    varying = sorted(f for f, ks in per_field.items() if len(ks) > 1)
    w = max(len(k) for k in keys)
    L = ["%s" % BEGIN, "",
         "> Generated by `Project Files/Scripts/build_schema_spec_counts.py` from the CSVs in",
         "> `Current TAPPs/`. Do not hand-edit: `validate_tapp.py` fails on drift",
         "> (`schema-spec-stale-counts`). Every figure the prose outside this block would otherwise",
         "> have to restate lives here.", "",
         "```",
         "TAPPs                        %d" % tapps,
         "content rows                 %d   (rows with a Keyed By value; group headers excluded)" % rows,
         "scalar, `(none)`             %d   %d%%" % (scalar, round(100 * scalar / rows)),
         "keyed (arrays in a schema)   %d   %d%%" % (rows - scalar, round(100 * (rows - scalar) / rows)),
         "Column G provenance stamps   %d   %d%%" % (stamped, round(100 * stamped / rows)),
         "distinct Keyed By strings    %d" % len(keys),
         "definer fields               %d" % len(definers),
         "",
         "keys in use library-wide (%d):" % len(in_use)]
    L += ["  %s" % k for k in sorted(in_use)]
    L += ["", "retired, and absent from every TAPP (%d):" % len(RETIRED)]
    L += ["  %s" % k for k in RETIRED]
    L += ["", "the complete set of Keyed By strings present, with row counts:"]
    L += ["  %-*s  %4d" % (w, k, n) for k, n in sorted(keys.items())]
    L += ["", "field names whose key is technique-dependent (%d) -- do NOT assume one" % len(varying),
          "global mapping of field name to key:"]
    L += ["  %-34s %s" % (f, " | ".join(sorted(per_field[f]))) for f in varying]
    L += ["", "definer fields, and what each enumerates:"]
    L += ["  %-34s %s" % (f, " | ".join(sorted(definers[f]))) for f in sorted(definers)]
    L += ["```", "", END]
    return "\n".join(L)


def main(apply=False):
    s = open(SPEC, encoding="utf-8").read()
    block = render()
    if BEGIN not in s:
        raise SystemExit("marker %s not found in %s -- insert it first" % (BEGIN, SPEC))
    cur = s[s.index(BEGIN):s.index(END) + len(END)]
    if cur == block:
        print("  schema spec counts up to date")
        return 0
    if not apply:
        old = set(cur.splitlines()); new = set(block.splitlines())
        for l in sorted(old - new):
            print("  - %s" % l)
        for l in sorted(new - old):
            print("  + %s" % l)
        print("  (check only -- pass --apply to write)")
        return 1
    open(SPEC, "w", encoding="utf-8").write(s.replace(cur, block))
    print("  schema spec counts regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main("--apply" in sys.argv))
