# E = how material reaches the measurement; A = how the analyser produces values
# E0 none (probe in place) · E1 one-time bulk · E2 parallel in-situ · E3 serial stepped · E4 continuous separation
# A1 simultaneous · A2 sequential scan · A3 multi-pass batch · A4c sweep that COLLAPSES · A4r sweep that IS REPORTED · A0 non-instrumental
C = {
"1":("E2","A2","EPMA — spot/raster; WDS spectrometer sequence (+EDS simultaneous)"),
"2":("E2","A1","SEM/FIB-SEM — EDS simultaneous; imaging is a raster"),
"3":("E2","A1","TEM/STEM — EDS/EELS"),
"4":("E3","A1","APT — field evaporation is serial, cumulative, destructive; ToF readout"),
"5":("E1","A2","Solution Q-ICP-MS — quadrupole mass scan"),
"5a":("E1","A3","Solution SF-ICP-MS — LR/MR resolution passes"),
"6":("E1","A1","MC-ICP-MS — cup array (+multi-dynamic = A3)"),
"7":("E2","A2","LA-Q-ICP-MS"),"7a":("E2","A3","LA-SF-ICP-MS"),"7b":("E2","A1","LA-MC-ICP-MS"),
"7c":("E2","A1","LA-ICP-ToF-MS — ToF simultaneous"),"7d":("E2","A2","LA-ICP-TQ-MS — + cell modes"),
"8":("E3","A3","Static NGMS — stepped heating/crushing x magnet steps  <-- the compound case"),
"10":("E3","A1","RI-TOF-NGMS — stepped extraction, ToF readout"),
"11":("E4","A2","GC-MS / GC-C-IRMS — chromatographic elution"),
"12":("E1","A4c","FTICR-MS — transient Fourier-transformed to frequency channels"),
"13":("E2","A4c","DESI-Orbitrap — surface desorption; FT readout"),
"14":("E4","A2","LC-MS"),
"15":("E2","A1","uL2MS — laser desorption spot, ToF"),
"16":("E3","A2","Pyrolysis-GC-MS — stepped pyrolysis THEN chromatography: E3 and E4 stacked"),
"17":("E1","A3","TIMS — peak jumping / multi-dynamic"),
"18":("E1","A1","AMS"),
"19":("E1","A1","EA-IRMS — combustion then GC separation, multicollector"),
"20":("E2","A1","LAF-IRMS — laser fluorination spot"),
"21":("E4","A2","CE-MS"),"22":("E4","A4r","IC — conductivity vs retention time IS the report"),
"23":("E2","A1","SIMS/NanoSIMS — depth profiling makes it E3"),
"24":("E2","A1","ToF-SIMS — depth profiling makes it E3"),
"25":("E2","A2","SNMS — depth profiling makes it E3"),
"27":("E0","A0","Fission track — etch then count optically; non-instrumental readout"),
"28":("E0","A1","Raman — dispersed spectrum read simultaneously on CCD"),
"29":("E0","A4r","VNMIR — reflectance vs wavelength IS the report"),
"30":("E0","A4r","NanoIR — absorption vs wavenumber, mapped"),
"31":("E0","A4c","NMR — FID Fourier-transformed"),
"32":("E0","A4r","XANES — absorption vs incident energy IS the report"),
"33":("E0","A4r","Mossbauer — absorption vs source velocity IS the report"),
"34":("E0","A2","XPS — binding-energy scan"),
"35":("E0","A1","CL — dispersed spectrum"),
"36":("E0","A4r","XRD — intensity vs 2theta IS the report"),
"37":("E0","A1","XRF — EDS simultaneous (WDS variant is A2)"),
"38":("E0","A4c","XCT — angle sweep collapses in reconstruction  <-- the only A4 built"),
"38a":("E0","A4c","Synchrotron XCT"),
"38b":("E0","A1","Muon X-ray Emission Spectroscopy"),
"38c":("E0","A4c","NCT+XCT — dual modality, both collapse"),
"39":("E0","A1","VLM"),"40":("E0","A1","UVFM"),
"41":("E0","A4c","Structured Light Scanning — projected pattern sequence collapses to a mesh"),
"42":("E0","A1","QRIS"),
"43":("E0","A4c","Lock-in Thermography — modulation frequency collapses to amplitude/phase"),
"44":("E0","A4c","CLSM — z-stack collapses to a 3D volume"),
"45":("E0","A1","PSFD"),
"46":("E1","A3","Gas Pycnometry — repeated gas expansions"),
"47":("E0","A4r","Seismic velocities — V vs confining pressure IS the report"),
"48":("E2","A4r","Nanoindentation — load-displacement curve per indent IS the report"),
"49":("E0","A1","Angle of Repose"),
"50":("E0","A4r","Compression Test — stress-strain curve IS the report"),
"51":("E0","A4r","Direct Shear — stress vs displacement IS the report"),
"52":("E2","A4r","AFM — force-distance curve per point"),
"53":("E2","A1","S-XRF mapping — rastered, simultaneous readout"),
"54":("E0","A4r","DSC — heat flow vs temperature IS the report"),
"55":("E0","A4r","TGA — mass vs temperature IS the report"),
"56":("E0","A4r","Thermal conductivity vs temperature"),
"57":("E0","A4r","Capacitance Dilatometry — dimension vs temperature"),
"59":("E1","A3","INAA — irradiate once, then COUNT REPEATEDLY at different decay times"),
"61":("E1","A0","Wet chemistry / gravimetric — non-instrumental readout"),
"62":("E0","A2","PGNAA — in-beam gamma spectrum"),
"63":("E4","A1","HPLC"),
"TDM":("E0","A4r","Temperature-Dependent Magnetization — M vs T IS the report"),
}
BUILT = {"1","2","3","5","5a","6","7","7a","7b","38"}

# Source data for Design Notes/Landscape_Acquisition_Architecture_2026-09-01.md.
# Kept so the classification can be re-derived, extended or corrected rather than re-typed:
# C maps planning-table row number -> (extraction architecture, analysis architecture, note).
# BUILT lists the rows that have a TAPP as of 2026-09-01.
