R = {
# --- CollisionCell: authored 2026-08-27, deliberately not split at build time ------------------
(1,2):("D","","M3 — defines the STD mode"),
(1,3):("D","","M3 — defines the KED mode, mechanism included"),
(1,4):("D","","M3 — defines the DRC mode"),
(1,5):("P","","M2 — what an MS/MS second mass filter adds"),
(1,6):("D","","M3 — scope: gas types, flows and voltages live in Group 4"),
(1,7):("D","","M3 — instruction: sentinel value where no cell is fitted"),
(2,2):("P","","M2 — which gas is standard and why (low mass, chemically inert)"),
(2,3):("D","","M3 — instruction: sentinel values"),
(3,2):("P","","M2 — interference suppression against analyte sensitivity"),
(3,3):("D","","M3 — instruction: sentinel values"),
(4,2):("D","","M3 — lists the reaction gases in use; a bare list is allowed content, not a practice claim"),
(4,3):("D","","M3 — instruction: sentinel values"),
(5,2):("D","","M3 — instruction: sentinel values"),
(6,2):("P","","M2 — how the bias discriminates, and what it controls"),
(6,3):("D","","M3 — instruction: sentinel values"),
# --- CompositionQC: merged 2026-08-27 from already-split TAPP text ----------------------------
(7,2):("D","","M3 — instruction: state units and whether estimated or measured"),
(7,3):("D","","M3 — scope: the method lives in Detection Limit Method"),
(7,4):("D","","M3 — instruction: sentinel value"),
(8,2):("D","","M3 — consistency instruction against Detection Limit"),
(9,2):("D","","M3 — defines how the quantity is computed"),
(9,3):("D","","M3 — scope boundary against observed scatter; the interpretation already moved to Purpose in the 2026-08-27 Step 2"),
(10,2):("D","","M3 — instruction: what to give"),
(11,2):("D","","M3 — instruction: sentinel value"),
(12,2):("D","REWRITE-STRADDLE","instruction on what to give, plus the reason ('since results calibrated against different published values ... are not directly comparable')"),
# --- ICPMS: merged 2026-08-26 from TAPP text already split on 2026-08-25 -----------------------
(13,2):("D","","M3 — scope boundary against the coolant and carrier gas fields"),
(14,2):("D","","M3 — instruction: specify the bracketing scheme"),
(15,2):("D","","M3 — instruction: record ratio and threshold"),
(15,3):("D","","M3 — scope: measured values live in Oxide Production"),
(15,4):("D","","M3 — lists the monitored ratios in use"),
(16,2):("D","","M3 — instruction: document independently of RF Power"),
(17,2):("D","","M3 — instruction: state where in the sequence the filter applies"),
(18,2):("D","","M3 — instruction: state both cones"),
(19,2):("D","","M3 — conditional instruction on recording the basis"),
(20,2):("D","","M3 — instruction: what to specify"),
(20,3):("D","","M3 — instruction: report biases and causes"),
(20,4):("D","","M3 — instruction: which form the offset takes"),
(21,2):("D","","M3 — instruction: state what is subtracted, over what interval, at what granularity"),
(22,2):("D","","M3 — selection criterion for an isotope-ratio internal standard"),
(22,3):("D","","M3 — instruction: sentinel value plus the alternative used"),
(23,2):("D","REWRITE-REDUNDANT(D=Basic)","'Mandatory at analysis level' names the tier; the CONDITION ('when concentrations near the LOD are reported') is real content and is never stripped under W3"),
(24,2):("D","","M3 — where mitigation is applied and how"),
(24,3):("D","","M3 — instruction: record flagging or exclusion at processing level"),
(25,2):("D","","M3 — instruction for the single-strategy case"),
(25,3):("D","","M3 — instruction: sentinel value for ratio-only procedures"),
(26,2):("D","","M3 — instruction: state the interval type and name the criterion"),
(27,2):("D","","M3 — instruction: name the reference material"),
(28,2):("D","","M3 — instruction: name each species and the mass affected"),
(29,2):("D","","M3 — scope: per-mass detail lives in two named fields"),
(30,2):("D","","M3 — defines the two reduction routes"),
(30,3):("D","","M3 — instruction: sentinel value"),
(31,2):("D","","M3 — instruction: state the mode, and each where analytes differ"),
(32,2):("P","","M2 — which material is standard for which matrix, and why platinum resists corrosion"),
(32,3):("D","","M3 — instruction: state both, one statement acceptable where identical"),
(33,2):("D","","M3 — constraint on the value: adjustments must preserve the bracketing strategy"),
# --- LaserAblation: 10 fields transferred 2026-08-27, never routed -----------------------------
(34,2):("D","REWRITE-REDUNDANT(D=Editable)","'Editable to accommodate' names the tier outright; which variations are legitimate is real content"),
(35,2):("D","","M3 — scope boundary against the carrier and make-up gas fields"),
(36,2):("D","","M3 — defines the background schedule for spot and transect work"),
(36,3):("D","","M3 — defines the background schedule for mapping"),
(36,4):("D","REWRITE-REDUNDANT(D=Editable)","'Editable to allow session-specific adjustment' is wholly the tier; nothing else is asserted"),
(37,2):("P","","M2 — which carrier gas is standard and why"),
(37,3):("D","REWRITE-REDUNDANT(C=Basic + D=Editable)","'flow rates are procedure targets; actual session values may be adjusted' is the C/D split in words; the +/-10% bound is real content"),
(38,2):("D","REWRITE-STRADDLE; REWRITE-REDUNDANT(C=N/A + D=Basic)","'This is an analysis-level parameter' restates the tiers; why it depends on the grain size is rationale"),
(38,3):("D","REWRITE-REDUNDANT(C=N/A + D=Basic)","'the procedure fixes ...; the map area is chosen at analysis time' is the C/D split in words; which parameters the procedure fixes is real content"),
(39,2):("D","","M3 — instruction: what to describe for multi-run designs"),
(39,3):("D","","M3 — scope: not applicable to raster mapping"),
(40,2):("P","","M2 — why smoothing devices are incompatible with high-resolution mapping"),
(40,3):("D","","M3 — instruction: report 'None' explicitly for mapping"),
(41,2):("D","","M3 — instruction: reference the software function or publication"),
}
