"""Procedure facts stated in each Solution MC paper's MC-ICP-MS methods, instrument tables and table notes (read
2026-09-30). Same format as ../SQ_Cells_RoundTrip_2026-09-30/facts.py. NOT blind. Keys are Solution MC column numbers 1–14."""

FACTS = {
  1: [
    ('Instrument Model', None, ['Neptune Plus'], 'budde2016'),
    ('Nebulizer Type', None, ['C-Flow'], 'budde2016'),
    ('Desolvation System', 'all', ['Aridus II'], 'budde2016'),
    ('Interface Cone Configuration', None, ['(H) skimmer'], 'budde2016'),
    ('Sample Uptake Rate', None, ['50'], 'budde2016'),
    ('Number of Cycles per Block', 'all', ['100'], 'budde2016'),
    ('Integration Time per Cycle', 'all', ['8.4 s'], 'budde2016'),
    ('Baseline Measurement Approach', None, ['on-peak-zero', 'on-peak zero'], 'budde2016'),
    ('Internal Normalization Element and Isotope Ratio', None, ['1.453173'], 'budde2016'),
    ('Mass Fractionation Law', None, ['exponential'], 'budde2016'),
    ('Spectral Interference Corrections Applied', None, ['91Zr'], 'budde2016'),
    ('Monitored Masses', '99Ru', ['99Ru'], 'budde2016'),
    ('Monitored Masses', '92Mo', ['92Mo'], 'budde2016'),
    ('Primary Calibration Standard Name', 'all/Mo', ['Alfa Aesar'], 'budde2016'),
    ('Between-Session (Long-Term) Analytical Precision and Assessment Method', 'BHVO-2/all', ['0.39'], 'budde2016'),
    ('Analytical Accuracy and Assessment Method', 'BHVO-2/all', ['indistinguishable'], 'budde2016'),
    ('Chromatographic Separation Applied', None, ['TRU'], 'budde2016'),
    ('Sample Aliquot Mass or Volume', None, ['100 ng'], 'budde2016'),
    ('Digestion Vessel Type', None, ['Savillex'], 'budde2016'),
  ],
  2: [
    ('Instrument Model', None, ['NEPTUNE'], 'craddock2008'),
    ('RF Power', None, ['1150'], 'craddock2008'),
    ('Coolant (Plasma) Gas Flow Rate', None, ['15'], 'craddock2008'),
    ('Auxiliary Gas Flow Rate', None, ['0.8'], 'craddock2008'),
    ('Nebulizer Gas Flow Rate', None, ['0.8–0.9'], 'craddock2008'),
    ('Guard Electrode', None, ['grounded'], 'craddock2008'),
    ('Interface Cone Configuration', None, ['X-cones'], 'craddock2008'),
    ('Nebulizer Type', None, ['PFA-50'], 'craddock2008'),
    ('Spray Chamber Type and Cooling Temperature', None, ['cyclonic'], 'craddock2008'),
    ('Sample Uptake Rate', None, ['50'], 'craddock2008'),
    ('Mass Resolution Setting', None, ['High'], 'craddock2008'),
    ('Collector Configuration', '33S', ['C'], 'craddock2008'),
    ('Number of Cycles per Block', 'all', ['20'], 'craddock2008'),
    ('Integration Time per Cycle', 'all', ['8.5'], 'craddock2008'),
    ('Baseline Measurement Approach', None, ['5 s'], 'craddock2008'),
    ('Wash Time Between Samples', None, ['2 min'], 'craddock2008'),
    ('Interfering Species', '32S', ['16O16O'], 'craddock2008'),
    ('Interfering Species', '33S', ['32S1H'], 'craddock2008'),
    ('Spike / Outlier Filtering Approach', None, ['no automatic'], 'craddock2008'),
    ('Mass Bias Correction Strategy', None, ['linear interpolation'], 'craddock2008'),
    ('Between-Session (Long-Term) Analytical Precision and Assessment Method', 'Alfa/δ34S', ['0.21'], 'craddock2008'),
    ('Digestion Temperature', 'HNO3–HCl digestion', ['70 °C'], 'craddock2008'),
    ('Chromatographic Separation Applied', None, ['AG50-X8'], 'craddock2008'),
    ('Secondary Reference Materials', 'NBS-123', ['NBS-123'], 'craddock2008'),
    ('Monitored Masses', '34S', ['34S'], 'craddock2008'),
    ('Analysis Inclusion and Rejection Criteria', None, ['0.5‰'], 'craddock2008'),
  ],
  3: [
    ('Instrument Model', None, ['Neptune'], 'hopp2021'),
    ('Acquisition Pass', 'HR', ['HR'], 'hopp2021'),
    ('Desolvation System', 'HR', ['Apex'], 'hopp2021'),
    ('Plasma Thermal Mode', 'MR', ['wet'], 'hopp2021'),
    ('Number of Cycles per Block', 'MR', ['50'], 'hopp2021'),
    ('Number of Cycles per Block', 'HR', ['25'], 'hopp2021'),
    ('Integration Time per Cycle', 'all', ['8.369'], 'hopp2021'),
    ('Faraday Cup Amplifier Resistor Values', '56Fe', ['10^10'], 'hopp2021'),
    ('Faraday Cup Amplifier Resistor Values', '60Ni', ['10^12'], 'hopp2021'),
    ('Sample Uptake Rate', None, ['100'], 'hopp2021'),
    ('Wash Time Between Samples', None, ['210'], 'hopp2021'),
    ('Internal Normalization Element and Isotope Ratio', None, ['0.023095'], 'hopp2021'),
    ('Mass Fractionation Law', None, ['exponential'], 'hopp2021'),
    ('Interfering Species', '54Fe', ['54Cr'], 'hopp2021'),
    ('Interference Correction Method', '58Fe', ['60Ni'], 'hopp2021'),
    ('Final Solution Matrix', 'all', ['0.45 M'], 'hopp2021'),
    ('Digestion Temperature', 'basalt HF–HNO3', ['150'], 'hopp2021'),
    ('Digestion Duration', 'iron aqua regia', ['24'], 'hopp2021'),
    ('Chromatographic Separation Applied', None, ['AG1-X8'], 'hopp2021'),
    ('Baseline Measurement Approach', None, ['On peak zero'], 'hopp2021'),
    ('Analytical Accuracy and Assessment Method', 'BHVO-2/μ54Fe(7/6)', ['2 ± 2'], 'hopp2021'),
    ('Uncertainty Level', None, ['Student'], 'hopp2021'),
    ('Monitored Masses', '53Cr', ['53Cr'], 'hopp2021'),
    ('Monitored Masses', '58Fe', ['58Fe'], 'hopp2021'),
  ],
  4: [
    ('Instrument Model', None, ['Neptune Plus'], 'hu2021'),
    ('Desolvation System', 'all', ['Apex'], 'hu2021'),
    ('Number of Cycles per Block', 'main configuration', ['40'], 'hu2021'),
    ('Integration Time per Cycle', 'all', ['8.184'], 'hu2021'),
    ('Baseline Measurement Approach', None, ['60 s'], 'hu2021'),
    ('Wash Time Between Samples', None, ['300'], 'hu2021'),
    ('Acquisition Pass', 'subconfiguration', ['subconfiguration'], 'hu2021'),
    ('Isotope Ratio Reported', 'φSm', ['152Sm/148Sm'], 'hu2021'),
    ('Isotope Ratio Reported', 'φYb', ['174Yb/172Yb'], 'hu2021'),
    ('Interfering Species', '162Dy', ['162Er'], 'hu2021'),
    ('Interference Correction Method', '164Dy', ['166Er'], 'hu2021'),
    ('Analytical Accuracy and Assessment Method', 'BCR-2/all', ['0.05'], 'hu2021'),
    ('Digestion Temperature', 'HF–HNO3–HClO4 attack', ['160'], 'hu2021'),
    ('Chromatographic Separation Applied', None, ['Ln-Spec'], 'hu2021'),
    ('Uncertainty Level', None, ['95%'], 'hu2021'),
    ('Target Species', 'Gd', ['Gd'], 'hu2021'),
    ('Monitored Masses', '163Dy', ['163Dy'], 'hu2021'),
  ],
  5: [
    ('Instrument Model', None, ['Nu Plasma II'], 'ibanezmejia2019'),
    ('Desolvation System', 'all', ['Aridus II'], 'ibanezmejia2019'),
    ('Number of Cycles per Block', 'all', ['50'], 'ibanezmejia2019'),
    ('Integration Time per Cycle', 'all', ['5 s'], 'ibanezmejia2019'),
    ('Double-Spike Isotope Pair', None, ['91Zr-96Zr', '91Zr–96Zr'], 'ibanezmejia2019'),
    ('Double-Spike Mixing Ratio', None, ['0.43'], 'ibanezmejia2019'),
    ('Final Solution Matrix', 'all', ['60 ng/g'], 'ibanezmejia2019'),
    ('Digestion Duration', 'Zr-only dissolution', ['60 h'], 'ibanezmejia2019'),
    ('Digestion Duration', 'U-Pb dissolution', ['48 h'], 'ibanezmejia2019'),
    ('Digestion Temperature', 'chemical abrasion', ['900'], 'ibanezmejia2019'),
    ('Collector Configuration', '95Mo', ['0.5 amu'], 'ibanezmejia2019'),
    ('Additional Notes', None, ['63.4'], 'ibanezmejia2019'),
    ('Within-Session Analytical Precision and Assessment Method', 'ZrNIST/all', ['2σ'], 'ibanezmejia2019'),
    ('Chromatographic Separation Applied', None, ['Ln-Spec'], 'ibanezmejia2019'),
    ('Coupled Technique(s)', None, ['ID-TIMS'], 'ibanezmejia2019'),
    ('Isotope Ratio Reported', 'δ94/90Zr', ['94Zr/90Zr'], 'ibanezmejia2019'),
    ('Monitored Masses', '98Mo', ['98Mo'], 'ibanezmejia2019'),
    ('Combination Method', 'all', ['weighted mean'], 'ibanezmejia2019'),
  ],
  6: [
    ('Instrument Model', None, ['Neptune'], 'nie2019'),
    ('Collector Configuration', '85Rb', ['L2'], 'nie2019'),
    ('Collector Configuration', '88Sr', ['H1'], 'nie2019'),
    ('Faraday Cup Amplifier Resistor Values', '87Rb', ['10^11'], 'nie2019'),
    ('Number of Cycles per Block', 'all', ['25'], 'nie2019'),
    ('Integration Time per Cycle', 'all', ['4.194'], 'nie2019'),
    ('Wash Time Between Samples', None, ['60 s'], 'nie2019'),
    ('Sample Uptake Rate', None, ['100'], 'nie2019'),
    ('Spray Chamber Type and Cooling Temperature', None, ['quartz'], 'nie2019'),
    ('Mass Resolution Setting', None, ['Low'], 'nie2019'),
    ('Final Solution Matrix', 'all', ['0.3 M'], 'nie2019'),
    ('Interference Correction Method', '87Rb', ['0.085'], 'nie2019'),
    ('Digestion Temperature', 'Parr bomb', ['175–180'], 'nie2019'),
    ('Digestion Acid(s)', 'HCl–HNO3 attack', ['11 M HCl'], 'nie2019'),
    ('Blank / Background Correction Method', None, ['two bracketing'], 'nie2019'),
    ('Uncertainty Level', None, ['2σ/√n'], 'nie2019'),
    ('Analytical Accuracy and Assessment Method', 'PCC-1 + SRM984/δ87Rb', ['zero'], 'nie2019'),
    ('Secondary Reference Materials', 'GS-N', ['GS-N'], 'nie2019'),
    ('Chromatographic Separation Applied', None, ['Sr resin'], 'nie2019'),
    ('Monitored Masses', '88Sr', ['88Sr'], 'nie2019'),
  ],
  7: [
    ('Instrument Model', None, ['Neptune'], 'nowell2008'),
    ('Collector Configuration', '182W', ['L4'], 'nowell2008'),
    ('Collector Configuration', '187Os', ['Ax'], 'nowell2008'),
    ('Number of Blocks per Measurement', None, ['9'], 'nowell2008'),
    ('Number of Cycles per Block', 'all', ['5'], 'nowell2008'),
    ('Integration Time per Cycle', 'all', ['4 s'], 'nowell2008'),
    ('Internal Normalization Element and Isotope Ratio', None, ['3.083'], 'nowell2008'),
    ('Mass Fractionation Law', None, ['exponential'], 'nowell2008'),
    ('Nebulizer Type', None, ['PFA-50'], 'nowell2008'),
    ('Spray Chamber Type and Cooling Temperature', None, ['Cinnabar'], 'nowell2008'),
    ('Sample Uptake Rate', None, ['80'], 'nowell2008'),
    ('Interfering Species', '187Os', ['187Re'], 'nowell2008'),
    ('Interference Correction Method', '184Os', ['182W'], 'nowell2008'),
    ('Blank / Background Correction Method', None, ['abundance sensitivity'], 'nowell2008'),
    ('Between-Session (Long-Term) Analytical Precision and Assessment Method', 'UMd/187Os/188Os', ['0.113795'], 'nowell2008'),
    ('Analytical Accuracy and Assessment Method', 'DTM/187Os/188Os', ['−12'], 'nowell2008'),
    ('Monitored Masses', '185Re', ['185Re'], 'nowell2008'),
    ('ICP Tuning', None, ['peak-centering'], 'nowell2008'),
    ('Instrument Warm-up / Session Duration Limit', None, ['half an hour'], 'nowell2008'),
    ('Faraday Cup Gain Calibration Method', None, ['Virtual Amplifier'], 'nowell2008'),
  ],
  8: [
    ('Instrument Model', None, ['Nu Plasma'], 'nowell2008'),
    ('Nebulizer Type', None, ['Micromist'], 'nowell2008'),
    ('Sample Uptake Rate', None, ['400'], 'nowell2008'),
    ('Acquisition Pass', 'sequence 2', ['sequence 2'], 'nowell2008'),
    ('Collector Configuration', '183W', ['L2'], 'nowell2008'),
    ('Collector Configuration', '192Os', ['H2'], 'nowell2008'),
    ('Integration Time per Cycle', '187Os', ['8 s'], 'nowell2008'),
    ('Integration Time per Cycle', '190Os', ['4 s'], 'nowell2008'),
    ('Number of Cycles per Block', 'all', ['50'], 'nowell2008'),
    ('Mass Fractionation Law', None, ['exponential'], 'nowell2008'),
    ('Monitored Masses', '183W', ['183W'], 'nowell2008'),
    ('Interference Correction Method', '187Os', ['185Re'], 'nowell2008'),
    ('Within-Session Analytical Precision and Assessment Method', 'DTM/187Os/188Os', ['0.173910'], 'nowell2008'),
    ('Faraday Cup Array Configuration', None, ['Seven Faraday'], 'nowell2008'),
  ],
  9: [
    ('Instrument Model', None, ['Neptune Plus'], 'pringle2017'),
    ('RF Power', None, ['1200'], 'pringle2017'),
    ('Coolant (Plasma) Gas Flow Rate', None, ['16'], 'pringle2017'),
    ('Auxiliary Gas Flow Rate', None, ['1.01'], 'pringle2017'),
    ('Nebulizer Gas Flow Rate', None, ['1.03'], 'pringle2017'),
    ('Interface Cone Configuration', None, ['Jet'], 'pringle2017'),
    ('Nebulizer Type', None, ['MicroFlow'], 'pringle2017'),
    ('Acquisition Pass', 'APEX', ['APEX'], 'pringle2017'),
    ('Final Solution Matrix', 'APEX', ['4 ppb'], 'pringle2017'),
    ('Final Solution Matrix', 'spray chamber', ['10 ppb'], 'pringle2017'),
    ('Collector Configuration', '88Sr', ['H2'], 'pringle2017'),
    ('Number of Cycles per Block', 'all', ['20'], 'pringle2017'),
    ('Integration Time per Cycle', 'all', ['8.389'], 'pringle2017'),
    ('Spike / Outlier Filtering Approach', None, ['2σ'], 'pringle2017'),
    ('Interference Correction Method', '87Rb', ['88Sr'], 'pringle2017'),
    ('Between-Session (Long-Term) Analytical Precision and Assessment Method', 'pure Rb ICP-MS solution/δ87Rb', ['0.01'], 'pringle2017'),
    ('Analytical Accuracy and Assessment Method', 'SRM984 through chemistry/δ87Rb', ['0.00 ± 0.03'], 'pringle2017'),
    ('Digestion Temperature', 'HF/HNO3 attack', ['130'], 'pringle2017'),
    ('Chromatographic Separation Applied', None, ['DGA'], 'pringle2017'),
    ('Monitored Masses', '84Sr', ['84Sr'], 'pringle2017'),
    ('Additional Notes', None, ['−2000 V'], 'pringle2017'),
  ],
  10: [
    ('Instrument Model', None, ['Neptune Plus'], 'schonbachler2025'),
    ('Desolvation System', 'all', ['Aridus II'], 'schonbachler2025'),
    ('Sample Uptake Rate', None, ['0.05'], 'schonbachler2025'),
    ('Number of Cycles per Block', 'all', ['60'], 'schonbachler2025'),
    ('Integration Time per Cycle', 'all', ['4.2'], 'schonbachler2025'),
    ('Baseline Measurement Approach', None, ['30 s'], 'schonbachler2025'),
    ('Internal Normalization Element and Isotope Ratio', None, ['0.3381'], 'schonbachler2025'),
    ('Faraday Cup Amplifier Resistor Values', '99Ru', ['10^12'], 'schonbachler2025'),
    ('Final Solution Matrix', 'all', ['0.005 M HF'], 'schonbachler2025'),
    ('Digestion Temperature', 'high-PT HF–HNO3', ['220'], 'schonbachler2025'),
    ('Digestion Duration', 'HNO3–HCl', ['12 h'], 'schonbachler2025'),
    ('Interference Correction Method', 'other', ['0.21798'], 'schonbachler2025'),
    ('Within-Session Analytical Precision and Assessment Method', 'all/ε96Zr', ['1.00'], 'schonbachler2025'),
    ('Between-Session (Long-Term) Analytical Precision and Assessment Method', 'BCR-2/ε92Zr', ['0.2'], 'schonbachler2025'),
    ('Monitored Masses', '101Ru', ['101Ru'], 'schonbachler2025'),
    ('Analysis Inclusion and Rejection Criteria', None, ['2SD'], 'schonbachler2025'),
  ],
  11: [
    ('Instrument Model', None, ['Neoma'], 'vankooten2026'),
    ('Mass Resolution Setting', None, ['6,000'], 'vankooten2026'),
    ('Desolvation System', 'Mg', ['Apex Omega'], 'vankooten2026'),
    ('Desolvation System', 'Cr', ['Apex HF'], 'vankooten2026'),
    ('Number of Cycles per Block', 'Fe', ['200'], 'vankooten2026'),
    ('Number of Cycles per Block', 'Cr', ['100'], 'vankooten2026'),
    ('Integration Time per Cycle', '26Mg', ['16.7'], 'vankooten2026'),
    ('Baseline Measurement Approach', None, ['75 s'], 'vankooten2026'),
    ('Interfering Species', '58Fe', ['58Ni'], 'vankooten2026'),
    ('Interference Correction Method', '54Fe', ['53Cr'], 'vankooten2026'),
    ('Digestion Temperature', 'Parr bomb', ['210'], 'vankooten2026'),
    ('Digestion Duration', 'NaOH fusion', ['13 min'], 'vankooten2026'),
    ('Faraday Cup Amplifier Resistor Values', '25Mg', ['10^11'], 'vankooten2026'),
    ('Sample Uptake Rate', None, ['30'], 'vankooten2026'),
    ('Monitored Masses', '49Ti', ['49Ti'], 'vankooten2026'),
    ('Monitored Masses', '60Ni', ['60Ni'], 'vankooten2026'),
    ('Uncertainty Level', None, ['standard error'], 'vankooten2026'),
    ('Secondary Reference Materials', 'BHVO2', ['BHVO2'], 'vankooten2026'),
    ('Make-up Gas and Flow Rate', None, ['no auxiliary gas'], 'vankooten2026'),
  ],
  12: [
    ('Instrument Model', None, ['Neptune Plus'], 'broussard2026'),
    ('Desolvation System', 'all', ['APEX Omega'], 'broussard2026'),
    ('Final Solution Matrix', 'all', ['300 ppb'], 'broussard2026'),
    ('Interfering Species', '41K', ['40Ar1H'], 'broussard2026'),
    ('Interference Correction Method', '41K', ['shoulder'], 'broussard2026'),
    ('Chromatographic Separation Applied', None, ['AG50W-X8'], 'broussard2026'),
    ('Analytical Accuracy and Assessment Method', 'BHVO-2/δ41K', ['0.448'], 'broussard2026'),
    ('Digestion Temperature', 'HF–HNO3 attack', ['150'], 'broussard2026'),
    ('Digestion Acid(s)', 'H2O2 step', ['H2O2'], 'broussard2026'),
    ('Coupled Technique(s)', None, ['iCAP Q'], 'broussard2026'),
    ('Monitored Masses', '39K', ['39K'], 'broussard2026'),
    ('Mass Bias Correction Strategy', None, ['bracketing'], 'broussard2026'),
    ('Sample Aliquot Mass or Volume', None, ['7 mg'], 'broussard2026'),
  ],
  13: [
    ('Instrument Model', None, ['Neptune Plus'], 'barnes2025'),
    ('Desolvation System', 'K', ['APEX'], 'barnes2025'),
    ('Plasma Thermal Mode', 'Cu', ['wet'], 'barnes2025'),
    ('Final Solution Matrix', 'Cu', ['100 ppb'], 'barnes2025'),
    ('Mass Resolution Assignment', 'K', ['high'], 'barnes2025'),
    ('Digestion Temperature', 'HF–HNO3 attack', ['170'], 'barnes2025'),
    ('Digestion Duration', 'HF–HNO3 attack', ['48 h'], 'barnes2025'),
    ('Interfering Species', '41K', ['ArH'], 'barnes2025'),
    ('Chromatographic Separation Applied', None, ['AG50W-X8'], 'barnes2025'),
    ('Monitored Masses', '65Cu', ['65Cu'], 'barnes2025'),
    ('Sample Aliquot Mass or Volume', None, ['20.66'], 'barnes2025'),
    ('Secondary Reference Materials', 'BHVO-2', ['BHVO-2'], 'barnes2025'),
  ],
  14: [
    ('Instrument Model', None, ['Neptune Plus'], 'barnes2025'),
    ('Mass Resolution Setting', None, ['6,600'], 'barnes2025'),
    ('Number of Cycles per Block', 'all', ['40'], 'barnes2025'),
    ('Integration Time per Cycle', '44Ca', ['8.39'], 'barnes2025'),
    ('Integration Time per Cycle', '51V', ['4.19'], 'barnes2025'),
    ('Internal Normalization Element and Isotope Ratio', None, ['0.749766'], 'barnes2025'),
    ('Interference Correction Method', '50Ti', ['52Cr'], 'barnes2025'),
    ('Between-Session (Long-Term) Analytical Precision and Assessment Method', 'BHVO-2/ε50Ti', ['0.16'], 'barnes2025'),
    ('Secondary Reference Materials', 'Agua Zarcas', ['Agua Zarcas'], 'barnes2025'),
    ('Digestion Temperature', 'HF–HNO3 attack', ['170'], 'barnes2025'),
    ('Monitored Masses', '44Ca', ['44Ca'], 'barnes2025'),
    ('Acquisition Pass', 'configuration 2', ['configuration 2'], 'barnes2025'),
    ('Sample Aliquot Mass or Volume', None, ['5.2 mg'], 'barnes2025'),
  ],
}
