"""Procedure facts stated in each LA-Q paper's LA-ICP-MS methods, instrument table and table notes (read 2026-09-30).

One entry per fact: (field, member, tokens, source). A keyed field's facts name their member ("outer/inner" for a
two-level key); a fact is recovered if ANY token appears in the right place. Written by the author of the cells after
re-reading the papers, so NOT blind. Keys are the column numbers of LA-Q-ICP-MS (1–7); the U-Pb twin carries 1–6.
"""

FACTS = {
  1: [
    ('Instrument Model', None, ['X-series 2'], 'nakanishi'),
    ('Laser Manufacturer & Model', None, ['IFRIT'], 'nakanishi'),
    ('Laser Wavelength and Type', None, ['260 nm'], 'nakanishi'),
    ('Laser Pulse Duration', None, ['220 fs'], 'nakanishi'),
    ('Laser Fluence (Energy Density)', None, ['12 J'], 'nakanishi'),
    ('Laser Repetition Rate', 'all', ['20 Hz'], 'nakanishi'),
    ('Laser Spot Geometry', 'all', ['30 µm'], 'nakanishi'),
    ('Laser Spot Path / Ablation Mode', 'all', ['Spot'], 'nakanishi'),
    ('RF Power', None, ['1400 W'], 'nakanishi'),
    ('Carrier Gas and Flow Rate', None, ['0.6 L/min'], 'nakanishi'),
    ('Make-up Gas and Flow Rate', None, ['0.9–1.2'], 'nakanishi'),
    ('Auxiliary Gas Flow Rate', None, ['0.6–1.2'], 'nakanishi'),
    ('Coolant (Plasma) Gas Flow Rate', None, ['16 L/min'], 'nakanishi'),
    ('Coolant (Plasma) Gas Flow Rate', None, ['12–13'], 'nakanishi'),
    ('Interface Cone Configuration', None, ['micro-skimmer'], 'nakanishi'),
    ('Torch Type', None, ['quartz injector'], 'nakanishi'),
    ('Internal Standard Element', 'all', ['Ni'], 'nakanishi'),
    ('Internal Standard Approach', 'all', ['EPMA'], 'nakanishi'),
    ('Primary Calibration Standard Name', 'all/Ir', ['Warburton Range'], 'nakanishi'),
    ('Primary Calibration Standard Name', 'all/Re', ['Warburton Range'], 'nakanishi'),
    ('Secondary Reference Materials', None, ['Tawallah Valley'], 'nakanishi'),
    ('Internal (Within-Measurement) Analytical Precision and Assessment Method', 'all', ['2SE'], 'nakanishi'),
    ('Combination Method', 'Re/Os abundance ratio', ['mean'], 'nakanishi'),
    ('Monitored Masses', '⁵⁹Co', ['⁵⁹Co'], 'nakanishi'),
    ('Monitored Masses', '¹⁰¹Ru', ['¹⁰¹Ru'], 'nakanishi'),
    ('Monitored Masses', '¹⁰³Rh', ['¹⁰³Rh'], 'nakanishi'),
    ('Monitored Masses', '¹⁰⁵Pd', ['¹⁰⁵Pd'], 'nakanishi'),
    ('Monitored Masses', '¹⁸⁵Re', ['¹⁸⁵Re'], 'nakanishi'),
    ('Monitored Masses', '¹⁸⁹Os', ['¹⁸⁹Os'], 'nakanishi'),
    ('Monitored Masses', '¹⁹³Ir', ['¹⁹³Ir'], 'nakanishi'),
    ('Monitored Masses', '¹⁹⁵Pt', ['¹⁹⁵Pt'], 'nakanishi'),
    ('Monitored Masses', '¹⁹⁷Au', ['¹⁹⁷Au'], 'nakanishi'),
    ('Monitored Masses', '⁶¹Ni', ['⁶¹Ni'], 'nakanishi'),
    ('Monitored Masses', '²⁴Mg', ['²⁴Mg'], 'nakanishi'),
    ('Monitored Masses', '²⁹Si', ['²⁹Si'], 'nakanishi'),
    ('Monitored Masses', '³¹P', ['³¹P'], 'nakanishi'),
    ('Monitored Masses', '³³S', ['³³S'], 'nakanishi'),
    ('Target Species', 'Co', ['Co'], 'nakanishi'),
    ('Target Species', 'Ru', ['Ru'], 'nakanishi'),
    ('Target Species', 'Rh', ['Rh'], 'nakanishi'),
    ('Target Species', 'Pd', ['Pd'], 'nakanishi'),
    ('Target Species', 'Re', ['Re'], 'nakanishi'),
    ('Target Species', 'Os', ['Os'], 'nakanishi'),
    ('Target Species', 'Ir', ['Ir'], 'nakanishi'),
    ('Target Species', 'Pt', ['Pt'], 'nakanishi'),
    ('Target Species', 'Au', ['Au'], 'nakanishi'),
  ],
  2: [
    ('Instrument Model', None, ['8900'], 'liu2024'),
    ('Laser Manufacturer & Model', None, ['GenesisGEO'], 'liu2024'),
    ('Laser Wavelength and Type', None, ['343 nm'], 'liu2024'),
    ('Laser Fluence (Energy Density)', None, ['6.79'], 'liu2024'),
    ('Laser Spot Geometry', 'all', ['100 µm'], 'liu2024'),
    ('Laser Repetition Rate', 'all', ['1 Hz'], 'liu2024'),
    ('Laser Spot Path / Ablation Mode', 'all', ['single spot'], 'liu2024'),
    ('Ablation Duration per Spot', None, ['45 s'], 'liu2024'),
    ('Background Count Time', None, ['25 s'], 'liu2024'),
    ('Memory Effect Mitigation', None, ['25 s washout'], 'liu2024'),
    ('RF Power', None, ['1550 W'], 'liu2024'),
    ('Coolant (Plasma) Gas Flow Rate', None, ['15 L'], 'liu2024'),
    ('Auxiliary Gas Flow Rate', None, ['0.85'], 'liu2024'),
    ('Carrier Gas and Flow Rate', None, ['0.7 L'], 'liu2024'),
    ('Carrier Gas and Flow Rate', None, ['0.1 L'], 'liu2024'),
    ('Dwell Time per Mass', 'all', ['30 ms/10 ms'], 'liu2024'),
    ('Detector Configuration', None, ['Dual'], 'liu2024'),
    ('Oxide Production Method and Threshold', None, ['<0.3%'], 'liu2024'),
    ('Data Processing Software(s)', None, ['Iolite'], 'liu2024'),
    ('Internal Standard Element', 'all', ['Si (for Co, Ni, Cu, Zn)'], 'liu2024'),
    ('Internal Standard Element', 'all', ['Al (for the other'], 'liu2024'),
    ('Primary Calibration Standard Name', 'all/all', ['NIST SRM 612 and NIST SRM 614'], 'liu2024'),
    ('Fusion Flux and Dilution Ratio', None, ['Li'], 'liu2024'),
    ('Detection Limit Method', 'all', ['Pettke'], 'liu2024'),
    ('Limit of Quantification (LOQ) Method', 'U', ['10SD'], 'liu2024'),
    ('Limit of Quantification (LOQ) Method', 'Sc', ['3.3 × LOD'], 'liu2024'),
    ('Combination Method', 'Sc', ['mean of n = 9'], 'liu2024'),
    ('Secondary Reference Materials', 'AC-E', ['AC-E'], 'liu2024'),
    ('Secondary Reference Materials', 'GSR-1', ['GSR-1'], 'liu2024'),
    ('Secondary Reference Materials', 'JB-1b', ['JB-1b'], 'liu2024'),
    ('Secondary Reference Materials', 'GSR-3', ['GSR-3'], 'liu2024'),
    ('Secondary Reference Materials', 'AGV-2', ['AGV-2'], 'liu2024'),
    ('Secondary Reference Materials', 'W-2A', ['W-2A'], 'liu2024'),
    ('Target Species', 'Sc', ['Sc'], 'liu2024'),
    ('Target Species', 'Ni', ['Ni'], 'liu2024'),
    ('Target Species', 'La', ['La'], 'liu2024'),
    ('Target Species', 'Lu', ['Lu'], 'liu2024'),
    ('Target Species', 'U', ['U'], 'liu2024'),
    ('Analytical Accuracy and Assessment Method', 'AC-E/Sc', ['within 10%'], 'liu2024'),
    ('Analytical Accuracy and Assessment Method', 'W-2A/Sc', ['within 10%'], 'liu2024'),
  ],
  3: [
    ('Instrument Model', None, ['7900'], 'liu2025'),
    ('Laser Manufacturer & Model', None, ['Resonetic'], 'liu2025'),
    ('Laser Wavelength and Type', None, ['193 nm'], 'liu2025'),
    ('Laser Fluence (Energy Density)', None, ['2.5'], 'liu2025'),
    ('Laser Repetition Rate', 'all', ['7 Hz'], 'liu2025'),
    ('Carrier Gas and Flow Rate', None, ['He'], 'liu2025'),
    ('Make-up Gas and Flow Rate', None, ['N2 or Ar'], 'liu2025'),
    ('Laboratory', None, ['Hefei'], 'liu2025'),
    ('Internal Standard Element', 'all', ['Si, Fe'], 'liu2025'),
    ('Internal Standard Approach', 'all', ['EMP'], 'liu2025'),
    ('Primary Calibration Standard Name', 'all/Au', ['NIST 610'], 'liu2025'),
    ('Primary Calibration Standard Name', 'all/Cu', ['NIST 610'], 'liu2025'),
    ('Secondary Reference Materials', 'NIST 612', ['NIST 612'], 'liu2025'),
    ('Secondary Reference Materials', 'BCR-2G', ['BCR-2G'], 'liu2025'),
    ('Spike / Outlier Filtering Approach', None, ['micronugget'], 'liu2025'),
    ('Target Species', 'Au', ['Au'], 'liu2025'),
    ('Target Species', 'Cu', ['Cu'], 'liu2025'),
    ('Laser Spot Geometry', 'all', ['40 µm'], 'liu2025'),
    ('Detection Limit', 'Au', ['0.01 ppm'], 'liu2025'),
    ('Detection Limit', 'Cu', ['0.1 ppm'], 'liu2025'),
  ],
  4: [
    ('Instrument Model', None, ['7900'], 'liu2025'),
    ('Laser Manufacturer & Model', None, ['Resonetic'], 'liu2025'),
    ('Laser Wavelength and Type', None, ['193 nm'], 'liu2025'),
    ('Laser Fluence (Energy Density)', None, ['2.5'], 'liu2025'),
    ('Laser Repetition Rate', 'all', ['7 Hz'], 'liu2025'),
    ('Carrier Gas and Flow Rate', None, ['He'], 'liu2025'),
    ('Make-up Gas and Flow Rate', None, ['N2 or Ar'], 'liu2025'),
    ('Laboratory', None, ['Hefei'], 'liu2025'),
    ('Internal Standard Element', 'all', ['Si, Fe'], 'liu2025'),
    ('Internal Standard Approach', 'all', ['EMP'], 'liu2025'),
    ('Primary Calibration Standard Name', 'all/Au', ['NIST 610'], 'liu2025'),
    ('Primary Calibration Standard Name', 'all/Cu', ['NIST 610'], 'liu2025'),
    ('Secondary Reference Materials', 'NIST 612', ['NIST 612'], 'liu2025'),
    ('Secondary Reference Materials', 'BCR-2G', ['BCR-2G'], 'liu2025'),
    ('Spike / Outlier Filtering Approach', None, ['micronugget'], 'liu2025'),
    ('Target Species', 'Au', ['Au'], 'liu2025'),
    ('Target Species', 'Cu', ['Cu'], 'liu2025'),
    ('Laser Spot Geometry', 'all', ['20 µm'], 'liu2025'),
    ('Sampling Unit Selection Criteria', None, ['larger than 20'], 'liu2025'),
  ],
  5: [
    ('Instrument Model', None, ['7500ce'], 'liu2016'),
    ('Laser Manufacturer & Model', None, ['GeoLasPro'], 'liu2016'),
    ('Laser Wavelength and Type', None, ['193 nm'], 'liu2016'),
    ('Laser Repetition Rate', 'all', ['5 Hz'], 'liu2016'),
    ('Laser Energy', None, ['150 mJ'], 'liu2016'),
    ('Laser Fluence (Energy Density)', None, ['7–10'], 'liu2016'),
    ('Background Count Time', None, ['50 s'], 'liu2016'),
    ('Data Processing Software(s)', None, ['AMS'], 'liu2016'),
    ('Signal Integration Interval Method', None, ['plateau'], 'liu2016'),
    ('Calibration Standard Measurement Frequency', None, ['before and after'], 'liu2016'),
    ('Primary Calibration Standard Name', 'all/all', ['NIST 610'], 'liu2016'),
    ('Detection Limit Method', 'all', ['3σ'], 'liu2016'),
    ('Procedure Reference(s)', None, ['Udry'], 'liu2016'),
    ('Laser Spot Geometry', 'all', ['24 and 32'], 'liu2016'),
    ('Laser Spot Geometry', 'all', ['90 µm'], 'liu2016'),
    ('Internal Standard Approach', 'all', ['100 wt% oxide'], 'liu2016'),
    ('Combination Method', 'La', ['average'], 'liu2016'),
    ('Detection Limit', 'La', ['0.113'], 'liu2016'),
    ('Detection Limit', 'Ba', ['0.049'], 'liu2016'),
  ],
  6: [
    ('Instrument Model', None, ['7500ce'], 'liu2016'),
    ('Laser Manufacturer & Model', None, ['GeoLasPro'], 'liu2016'),
    ('Laser Wavelength and Type', None, ['193 nm'], 'liu2016'),
    ('Laser Repetition Rate', 'all', ['5 Hz'], 'liu2016'),
    ('Laser Energy', None, ['150 mJ'], 'liu2016'),
    ('Laser Fluence (Energy Density)', None, ['7–10'], 'liu2016'),
    ('Background Count Time', None, ['50 s'], 'liu2016'),
    ('Data Processing Software(s)', None, ['AMS'], 'liu2016'),
    ('Signal Integration Interval Method', None, ['plateau'], 'liu2016'),
    ('Calibration Standard Measurement Frequency', None, ['before and after'], 'liu2016'),
    ('Primary Calibration Standard Name', 'all/all', ['NIST 610'], 'liu2016'),
    ('Detection Limit Method', 'all', ['3σ'], 'liu2016'),
    ('Procedure Reference(s)', None, ['Udry'], 'liu2016'),
    ('Laser Spot Geometry', 'all', ['~24'], 'liu2016'),
    ('Internal Standard Element', 'all', ['Ca'], 'liu2016'),
    ('Internal Standard Approach', 'all', ['EMP'], 'liu2016'),
    ('Target Material', 'sodium-merrillite', ['merrillite'], 'liu2016'),
  ],
  7: [
    ('Laser Manufacturer & Model', None, ['Analyte G2'], 'wu2023'),
    ('Ablation Cell Type', None, ['HelEx'], 'wu2023'),
    ('Laser Wavelength and Type', None, ['193 nm'], 'wu2023'),
    ('Laser Pulse Duration', None, ['4-5 ns', '4–5 ns'], 'wu2023'),
    ('Laser Fluence (Energy Density)', None, ['4 J'], 'wu2023'),
    ('Laser Repetition Rate', 'all', ['10 Hz'], 'wu2023'),
    ('Laser Spot Geometry', 'all', ['50, 90, 150'], 'wu2023'),
    ('Laser Spot Path / Ablation Mode', 'all', ['single hole'], 'wu2023'),
    ('Ablation Duration per Spot', None, ['25 s'], 'wu2023'),
    ('RF Power', None, ['1350 W'], 'wu2023'),
    ('Coolant (Plasma) Gas Flow Rate', None, ['15.00'], 'wu2023'),
    ('Auxiliary Gas Flow Rate', None, ['0.80'], 'wu2023'),
    ('Carrier Gas and Flow Rate', None, ['900'], 'wu2023'),
    ('Carrier Gas and Flow Rate', None, ['0.65'], 'wu2023'),
    ('Make-up Gas and Flow Rate', None, ['4.0 mL'], 'wu2023'),
    ('Signal Collection Mode', None, ['peak jump'], 'wu2023'),
    ('Total Integration Time per Output Data Point', None, ['0.659'], 'wu2023'),
    ('Mass Resolution Setting', None, ['300'], 'wu2023'),
    ('Reaction Gas Type', 'all', ['NH3'], 'wu2023'),
    ('Uncertainty Propagation Method', 'all', ['Rösel'], 'wu2023'),
    ('Primary Calibration Standard Name', 'all/Lu', ['NIST SRM 610'], 'wu2023'),
    ('Primary Calibration Standard Name', 'all/Hf', ['XN02'], 'wu2023'),
    ('Secondary Reference Materials', 'ARM-1', ['ARM-1'], 'wu2023'),
    ('Secondary Reference Materials', 'MG-1', ['MG-1'], 'wu2023'),
    ('Interference Correction Method', '(176+82)Hf', ['0.02655'], 'wu2023'),
    ('Interfering Species', '(176+82)Hf', ['176Yb'], 'wu2023'),
    ('Combination Method', 'Lu-Hf weighted-mean age', ['weighted mean'], 'wu2023'),
    ('Analytical Accuracy and Assessment Method', 'MG-1/common-Hf-corrected single-spot age', ['1.5%'], 'wu2023'),
    ('Dwell Time per Mass', '27Al', ['2 ms'], 'wu2023'),
    ('Dwell Time per Mass', '(176+82)Hf', ['300 ms'], 'wu2023'),
    ('Dwell Time per Mass', '(175+82)Lu', ['50 ms'], 'wu2023'),
    ('Dwell Time per Mass', '175Lu', ['1 ms'], 'wu2023'),
    ('Monitored Masses', '27Al', ['27Al'], 'wu2023'),
    ('Monitored Masses', '43Ca', ['43Ca'], 'wu2023'),
    ('Monitored Masses', '89Y', ['89Y'], 'wu2023'),
    ('Monitored Masses', '90Zr', ['90Zr'], 'wu2023'),
    ('Monitored Masses', '172Yb', ['172Yb'], 'wu2023'),
    ('Monitored Masses', '(172+82)Yb', ['(172+82)Yb'], 'wu2023'),
    ('Monitored Masses', '175Lu', ['175Lu'], 'wu2023'),
    ('Monitored Masses', '(175+82)Lu', ['(175+82)Lu'], 'wu2023'),
    ('Monitored Masses', '(176+82)Hf', ['(176+82)Hf'], 'wu2023'),
    ('Monitored Masses', '(177+82)Hf', ['(177+82)Hf'], 'wu2023'),
    ('Monitored Masses', '(178+82)Hf', ['(178+82)Hf'], 'wu2023'),
  ],
}

